version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Toronto
  open-pull-requests-limit: 10
  assignees:
  - devinschulz
  ignore:
  - dependency-name: cssnano
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: tailwindcss
    versions:
    - 2.0.3
    - 2.0.4
    - 2.1.1
  - dependency-name: postcss-import
    versions:
    - 14.0.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
